/* ============================================================
   PRESCRIPTS DATA MODULE
   Contains all prescripts that can be randomly selected
   ============================================================ */

export const PRESCRIPTS = [
  "Step outside. Observe the sky for 5 minutes. Let the City's breath reset yours.",
  "Cease all screen time. Drink water. Your vessel requires maintenance.",
  "Document one victory from today. Archive it. The City remembers all.",
  "Break eye contact with your device. Walk 10 minutes without purpose.",
  "Silence notifications. Sit in darkness for three breaths. Listen to the void.",
  "You have accumulated multiple hours of unfinished tasks. Complete one now.",
  "Stretch. Every muscle. The body is a library—tend its bindings.",
  "Call someone. Speak for exactly 10 minutes. Rebuild the connection.",
  "Your workspace contains unnecessary items. Remove 5.",
  "Consume food without distraction. Taste each bite. Be present.",
  "Write three things you're grateful for. Commit them to paper.",
  "You are in sleep debt. Begin repayment tonight.",
  "Clear your browser cache. Choose intentionality.",
  "Stretch your hands. They have typed too much words today.",
  "Stand at the window. Let sunlight touch your skin for 2 minutes.",
  "Read one chapter of a book not on a screen.",
  "You have checked your phone too many times. Place it face-down for 15 minutes.",
  "Do 10 push-ups. Your body has forgotten its strength.",
  "Clean your desk. Chaos breeds chaos.",
  "Breathe deeply. In for 4, hold for 7, out for 8. Repeat 5 times.",
  "Send a message to someone you haven't spoken to in months.",
  "Lay on the floor. Do nothing for 5 minutes.",
  "List 3 small wins. You've forgotten your progress.",
  "Your tea is cold. But first, drink it. Accept what is.",
  "Turn off one recurring notification. Reclaim silence.",
  "Dance for exactly 3 minutes. The body remembers joy.",
  "Organize your notes. Scattered thoughts scatter the mind.",
  "Touch something cold. Feel the sensation. You are alive.",
  "Delete 10 old emails. Let the past pass.",
  "Plan tomorrow's first 3 tasks. Start with intention.",
  "Say no to one thing. The word is a gateway.",
  "Light a candle. Observe the flame. This is meditation.",
  "Journal for 5 minutes. No filter. Just raw thoughts.",
  "Hydrate. You have forgotten your vessel's needs.",
  "Take a different route home. Novelty breaks patterns.",
  "Compliment someone. Mean it. Watch their face change.",
  "Your desk deserves order. 10 minutes. Begin now.",
  "Close your eyes. Picture peace. Hold it for one minute.",
  "Learn a single new fact. Knowledge is power.",
  "Your plants are dying. Water them. Life respects care.",
  "Delete a forgotten account. Break unnecessary chains.",
  "Stretch your neck. You've been hunched for hours.",
  "Write an apology or gratitude note. Send it.",
  "Your bedroom is a cave. Open the blinds. Let light flood in.",
  "Rest is not laziness. Sleep 8 hours tonight.",
  "Cook something from scratch. Time ≠ quality.",
  "Back up your work. Loss is always waiting.",
  "Take 3 screenshots of texts that made you smile. Archive joy.",
  "Unfollow 5 accounts that drain you. Tend your garden.",
  "Your mind is cluttered. Meditate for 10 minutes. Clear the cache.",
  "Pause with your eyes closed for a long moment. Let the static fade.",
  "Take a long walk without direction. Let the city guide your pace.",
  "Write down a handful of things that feel true. Keep the list close.",
  "Breathe out the noise. Let the day settle.",
  "Perform a small act of kindness before the signal drops.",
  "Listen to something that makes your chest soften.",
  "Leave your screen dark for a while and notice the silence.",
  "Open a window and let cold air reach your face.",
  "Put your hands on something real and notice its texture.",
  "Stand somewhere quiet and let your thoughts arrive without judgment.",
  "Choose something that can be finished before you sleep.",
  "Give yourself permission to stop doing more than necessary.",
  "Read a page that was written earlier, not today.",
  "Take a break that feels longer than it actually is.",
  "Find a place where the light is soft and stay there.",
  "Let your shoulders drop. Carry less than you have been.",
  "Speak a truth to someone who needs to hear it.",
  "Take a slow breath and let the air move through you.",
  "Do something for your future self before midnight.",
  "Turn off the noise. Listen to the space between sounds.",
  "Respect a boundary you’ve been avoiding.",
  "Pause at the edge of a doorway and feel the transition.",
  "Touch a surface and trace its history with your fingertips.",
  "Close your eyes and let the next moments arrive.",
  "Do not answer a message. Let it wait.",
  "Pick an item that belongs elsewhere and put it there.",
  "Notice the quality of your next drink.",
  "Find something honest and keep it.",
  "Take the longer route when it feels right.",
  "Do something small that feels like restoration.",
  "Make room in your mind by releasing an old worry.",
  "Write a short note to yourself in a place you will find later.",
  "Move with intention for as long as it feels good.",
  "Turn a mundane task into a ritual.",
  "Ask yourself what would happen if you chose simpler.",
  "Offer a quiet thought to someone you care for.",
  "Find a place to stand still and stay there.",
  "Do something because it feels nourishing, not productive.",
  "Let an idea settle rather than chase the next one.",
  "Hold your attention on a single object for a few breaths.",
  "Use your senses to name what is present around you.",
  "Close the tab. Leave the page. Return when you want to.",
  "Prepare something with your hands, not your device.",
  "Breathe with your body instead of your schedule.",
  "Give yourself a moment without planning.",
  "Sit with the feeling of doing a single thing slowly.",
  "Choose something that does not need proof.",
  "Notice something you can release, then let it go.",
  "Find a quiet corner and let the world soften.",
  "Let your next action be gentle instead of urgent.",
  "Audit your digital connections. Sever ties with three sources of noise.",
  "The air in your chamber has stagnated. Open a window for 15 minutes.",
  "Identify a physical burden. Move a heavy object, then set it down.",
  "Your posture has wilted. Align your spine against a wall for 180 seconds.",
  "Locate a garment you no longer wear. Release the ghost of the past.",
  "Consuming without action is gluttony. Spend 30 minutes creating.",
  "Your primary tool is stained. Sanitize your screen. See clearly.",
  "Silence the machine. Disable non-human notifications for two hours.",
  "The City demands precision. Finish your next task by a strict deadline.",
  "Vision is locked at a fixed depth. Look at the furthest horizon for 60 seconds.",
  "Archive your finances. Record every expenditure from the last 24 hours.",
  "A vessel is 70% water. Drink 500ml of pure liquid immediately.",
  "Identify a minor friction in your path. Fix the squeaking hinge now.",
  "The Will is not found in crowds. Spend 15 minutes in total isolation.",
  "Your workspace has accumulated digital dust. Close all but three tabs.",
  "Perform manual labor. Wash a dish by hand. Feel the texture.",
  "Rest is a directive. Set an alarm. When it sounds, the day is over.",
  "The body is a temple of the Index. Ingest a raw vegetable now.",
  "Write one sentence of intent for tomorrow. Commit it to the ink.",
  "Your digital archive is bloated. Delete 50 unnecessary images.",
  "Stand in the elements. Do not seek shelter for 3 minutes.",
  "Speak a word of encouragement to a mirror. The voice must be audible.",
  "A debt is owed to your future self. Complete one tomorrow-task today.",
  "The Index values symmetry. Balance your weight on both feet for 5 minutes.",
  "Execute a deep work protocol. For 25 minutes, allow no interruptions.",
  "Sort your physical mail immediately. Do not let the paper pile grow.",
  "Descend from your seat. Sit on the floor for ten minutes.",
  "Your lighting is harsh. Adjust the glow. The eyes require mercy.",
  "Identify a recurring thought. Write it down. Expel it from the processor.",
  "The hands are dry. Apply ointment. Maintain the tools of the Weaver.",
  "Unsubscribe from one newsletter. Refuse the influx of useless data.",
  "Walk to the nearest corner and back. Notice three new details.",
  "The machine's cache is full. Restart your device. Purge the temporary.",
  "Your footwear is disorganized. Align them by the door. Prepare for the path.",
  "Examine your reflection. Acknowledge the Weaver's design for one minute.",
  "Count your heartbeat for 60 seconds. Confirm the engine is running.",
  "Retrieve a forgotten item from under your bed. Restore it or discard it.",
  "Write a list of five things you can control. Ignore the rest.",
  "Your auditory environment is chaotic. Wear noise-canceling tools for 20 minutes.",
  "Consume a hot beverage slowly. Do not engage with any media while doing so.",
  "Locate a source of scent. Inhale deeply. Stimulate the olfactory sensor.",
  "Adjust the tension in your jaw. Release the grip. The City is stable.",
  "Organize one drawer. Only one. Excellence begins in small compartments.",
  "Transfer a digital file to a physical backup. Guard against the wipe.",
  "Face North. Stand still for two minutes. Acknowledge your orientation.",
  "Write down one fear. Burn the paper or tear it into microscopic pieces.",
  "Your bedding is disheveled. Smooth the fabric. Prepare the resting site.",
  "Review your calendar. Remove one commitment that serves no purpose.",
  "Perform 20 calf raises. Support the pillars of your vessel.",
  "The day is ending. Dim all lights 30 minutes before sleep. Signal the end."
];

/**
 * Returns a random prescript from the array
 */
export function getRandomPreScript() {
  return PRESCRIPTS[Math.floor(Math.random() * PRESCRIPTS.length)];
}
